/// NOTE: THIS FILE IS AUTO-GENERATED BY dev/generate-oraclerowsequence-multi-decode.sh

#if compiler(<5.9)
extension AsyncSequence where Element == OracleRow {
    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0)> {
        self.map { row in
            try row.decode(T0.self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable>(_: (T0).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0)> {
        self.decode(T0.self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1)> {
        self.map { row in
            try row.decode((T0, T1).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable>(_: (T0, T1).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1)> {
        self.decode((T0, T1).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2)> {
        self.map { row in
            try row.decode((T0, T1, T2).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable>(_: (T0, T1, T2).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2)> {
        self.decode((T0, T1, T2).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable>(_: (T0, T1, T2, T3).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3)> {
        self.decode((T0, T1, T2, T3).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable>(_: (T0, T1, T2, T3, T4).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4)> {
        self.decode((T0, T1, T2, T3, T4).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5)> {
        self.decode((T0, T1, T2, T3, T4, T5).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6, T7).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6, T7).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6, T7).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6, T7).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, T11: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, T11: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, T11: OracleDecodable, T12: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, T11: OracleDecodable, T12: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, T11: OracleDecodable, T12: OracleDecodable, T13: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, T11: OracleDecodable, T12: OracleDecodable, T13: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13).self, context: .default, file: file, line: line)
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, T11: OracleDecodable, T12: OracleDecodable, T13: OracleDecodable, T14: OracleDecodable, JSONDecoder: OracleJSONDecoder>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14).Type, context: OracleDecodingContext<JSONDecoder>, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)> {
        self.map { row in
            try row.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14).self, context: context, file: file, line: line)
        }
    }

    @inlinable
    @_alwaysEmitIntoClient
    public func decode<T0: OracleDecodable, T1: OracleDecodable, T2: OracleDecodable, T3: OracleDecodable, T4: OracleDecodable, T5: OracleDecodable, T6: OracleDecodable, T7: OracleDecodable, T8: OracleDecodable, T9: OracleDecodable, T10: OracleDecodable, T11: OracleDecodable, T12: OracleDecodable, T13: OracleDecodable, T14: OracleDecodable>(_: (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14).Type, file: String = #fileID, line: Int = #line) -> AsyncThrowingMapSequence<Self, (T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)> {
        self.decode((T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14).self, context: .default, file: file, line: line)
    }
}
#endif
