#!/usr/bin/env bash
##===----------------------------------------------------------------------===##
##
## This source file is part of the OracleNIO open source project
##
## Copyright (c) 2024 Timo Zacherl and the OracleNIO project authors
## Licensed under Apache License v2.0
##
## See LICENSE for license information
## See CONTRIBUTORS.md for the list of OracleNIO project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##

set -euo pipefail

CURRENT_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$(git -C "${CURRENT_SCRIPT_DIR}" rev-parse --show-toplevel)"

# 1.
CONTRIBUTORS=$( cd "$CURRENT_SCRIPT_DIR"/.. && git shortlog -es | cut -f2 | sed 's/^/- /' )

# 2.
cat > "$REPO_ROOT/CONTRIBUTORS.md" <<- EOF
For the purpose of tracking copyright, this is the list of individuals and
organizations who have contributed source code to OracleNIO.

For employees of an organization/company where the copyright of work done
by employees of that company is held by the company itself, only the company
needs to be listed here.

## COPYRIGHT HOLDERS

### Contributors

$CONTRIBUTORS

**Updating this list**

Please do not edit this file manually. It is generated using \`bash ./scripts/generate-contributors-list.sh\`.
If a name is misspelled or appearing multiple times: add an entry in \`./.mailmap\`.
EOF
