name: Soundness

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  soundness:
    container:
      image: swift:jammy
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Mark repo safe in non-fake global config
      run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
    - name: Run soundness
      run: |
        scripts/soundness.sh
        exit $(git status --porcelain | wc -l)

  api-breakage:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container: swift:jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # https://github.com/actions/checkout/issues/766
      - name: API breaking changes
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          swift package diagnose-api-breaking-changes origin/main
